spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/sportify
    password: Develop!1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: create
  application:
    name: livestreaming
server:
  error:
    include-message: always

security:
  oauth2:
    client:
      registration:
        google:
          client-id: 1028122124245-bo25p50d2v3plni71uuvbtcqp0sa1t3k.apps.googleusercontent.com
          client-secret: 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
          scope: # 기본 값 openid,profile,email => profile, email 로 설정 변경
            - profile
            - email

        naver:
          client-id: LWZ4a2ytsZRgHCroT7OZ
          client-secret: JCYmdq6x1g
          client-authentication-method: client_secret_post
          authorization-grant-type: authorization_code
          redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          #            scope:
          #              - name
          #              - email
          #              - profile_image
          client-name: Naver

        kakao:
          client-id: 301a3262a29d50f0ae945467d2461d44
          client-secret: 6guoP5GKyebpIsdV0K5N4gAqz0JtBAas
          client-authentication-method: client_secret_post
          authorization-grant-type: authorization_code
          scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
            - profile_nickname
            - profile_image
            - account_email
          redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          client-name: Kakao

      provider:
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-info-authentication-method: header
          user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정

        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-info-authentication-method: header
          user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정